project:
  type: website
  output-dir: docs

website:
  site-path: "/personal-isaac-morris/"
  page-navigation: true
  navbar:
    background: black
    foreground: info
    logo: images/wwLogoNew.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles.qmd
        text: Articles
      - href: postsIndex.qmd
        text: Blog
      - comment.qmd
 
format:
  html:
    theme: lightly
    css: styles.css
    toc: true
