project:
  type: website
  output-dir: docs

website:
  title: "isaac morris warmup website"
  site-path: "/warmup-isaac-morris/"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles.qmd
        text: Articles
      - comment.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
