---
title: "Aritificial Intelligence & the Classroom"
description: "A post to desmistyify artificial intelligence for academic use."
date: "November 2023"
categories: 
    - technology
    - substantive
---
## A Revolutionary Issue

The education landscape has experienced drastic changes over the last few years. Following the covid shutdowns, many schools have adopted online resources to engage their students. These changes included online classes, assignments, tests, and projects. But several of these adaptations lack permanence with the free release of artificial intelligence chatbots; how can online quizzes or tests exist when intelligent, online bots capable of reading and answering complex questions can exist a tab away? Students, who are very aware of such technologies, are enabled to use ai to cheat on schoolwork (Mineo). This new growth of academic cheating is not limited to online work, but to any kind of homework in general.

As a natural response, many teachers have avoided the issue with a complete ban of the most popular ai chatbot, ChatGPT (Faguay). This is an understandable action; teachers and schools were not prepared for the release of ai technology. People are still figuring out what to do, as is obvious with the ban and then unban of Chat GPT in New York schools (Faguay). But responding to new technologies such as ai is not just an issue isolated towards our education system. How we adapt to change, or choose not to, will influence the minds of the next generation. So, is avoiding ai in professional or academic settings the right thing for people to do?

It is important to confront our fears of artificial intelligence by learning about it, as part of the stigma surrounding ai come from a place of ignorance. People do not understand artificial intelligence, its real potential dangers, its potential benefits, or even the devices they use to access it. This is not surprising since the only preparations society has made is demonstrating many fictitious scenarios in which it will take over the world. 

First, we need to define artificial intelligence. An article on Microsoft Azure demonstrates that ai is the capability of a computer system to mimic human cognitive functions such as learning and problem-solving (Azure). The history of artificial intelligence began inside entertainment media. But in the 1950’s a research team, including Alan Turing, began to explore the concept of whether technology could “think. (SITNFlash)” This excitement was ahead of its time, as the capabilities of technology were not keeping up with theory and research. But just over ten years later, one of the first ai chatbots was created. Eliza was created to be a psychotherapist chatbot and was revolutionary at the time. A machine with its interactibility had not been seen before; but its age is now made obvious by its limitations. Since then, artificial intelligence’s current capabilities have significantly grown. They include being able to recommend songs, social media posts, or movies/shows you might like, scanning endless amounts of information, enhancements for self-controlled vehicles, present possible diagnoses for hospital patients quicker than experts, and being interactive software that can carry conversations with people (called chatbots). There are many more capabilities, and the potential is endless, but how do the most advanced ai systems work? 

Ai like ChatGPT is created by machine learning. Machine learning, as defined by Arthur Samuel in the 1950’s, is “the field of study that gives computers the ability to learn without explicitly being programmed (Brown).” This process happens in three ways, and always by learning through experience. The first, called supervised learning, consists of people “teaching” the ai through data sets. The more data, the more accurate it gets to recognizing specific data points. The second is called unsupervised learning; it happens when ai is taught to recognize patterns and is given data to learn on its own. Lastly, there is reinforcement. Reinforcement involves the use of tests or games and reward systems to instruct ai on using data (Brown).

After having a better understanding of how ai is built, chatbots like ChatGPT become demystified. But for the sake of learning more about ai and context behind some of its most relevant applications, feel free to learn more about chatbots by using Eliza and ChatGPT.

For teachers who are on the fence about artificial intelligence’s role in the classroom, here is a study tool that uses ai. To use it, upload a study document to the website, following its instructions. It will then scan the documents for information and create study cards like those on Quizlet. This is just one application of artificial intelligence that can be used to show your students how to use technology responsibly. It is important to not shy away from use of ai, despite its potential use for cheating in academic settings, stealing money or information, or taking over the world. Again, teachers, your students are going to cheat in your classrooms. They have been using Quizlet and Chegg long before touching ChatGPT. It is your responsibility to adapt to such technologies, as your students are continually doing so. To villainize ai and ban students from using it in any kind of formal or academic context would be cheating them; specifically, it teaches that adaptability is not important and takes away their opportunity to get aquatinted with technology they will likely be using in their career. Currently, 67% of businesses are now using machine learning, and it will only become more widely used by the next generation (Brown). Teachers, it is important to show the next generation how to use artificial intelligence responsibly in academic settings; because even though others in the past tried to say otherwise, they will be carrying this new technology around in their pockets- along with their calculators.

## Sources:

“Artificial Intelligence vs. Machine Learning: Microsoft Azure.” Artificial Intelligence vs. Machine Learning | Microsoft Azure, azure.microsoft.com/en-us/resources/cloud-computing-dictionary/artificial-intelligence-vs-machine-learning. Accessed 15 Nov. 2023.

Brown, Sara. “Machine Learning, Explained.” MIT Sloan, 21 Apr. 2021, mitsloan.mit.edu/ideas-made-to-matter/machine-learning-explained. 

“Eliza: A Very Basic Rogerian Psychotherapist Chatbot.” Eliza, a Chatbot Therapist, web.njit.edu/~ronkowit/eliza.html. Accessed 15 Nov. 2023.

Faguy, Ana. “New York City Public Schools Reverses Chatgpt Ban.” Forbes, Forbes Magazine, 5 Oct. 2023, www.forbes.com/sites/anafaguy/2023/05/18/new-york-city-public-schools-reverses-chatgpt-ban/?sh=63d433fb71da.

Mineo, Liz. “Time for Teachers to Get Moving on Chatgpt.” Harvard Gazette, 8 Sept. 2023, news.harvard.edu/gazette/story/2023/09/time-for-teachers-to-get-moving-on-chatgpt/.

SITNFlash. “The History of Artificial Intelligence.” Science in the News, 23 Apr. 2020, sitn.hms.harvard.edu/flash/2017/history-artificial-intelligence/.

# Other Links:

https://www.revision.ai/

https://web.njit.edu/~ronkowit/eliza.html

https://chat.openai.com/